using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.HtmlControls;
using System.IO;


namespace WebApp.Pages
{
    public partial class ShoppingCart : System.Web.UI.Page
    {
        string source =ContantsUtils.DATABASE_PATH;
        SqlConnection cn = new SqlConnection();
        DataTable table;
        string clientId;
        SqlDataAdapter da;
        protected void Page_Load(object sender, EventArgs e)
        {
            clientId = Session["UserID"].ToString();
            cn = new SqlConnection(source);
            SqlCommand cmd = new SqlCommand("Select Cart1.Id,Cart1.ProductId,Product1.Name,Product1.Price,Cart1.qty,Cart1.Amount from Cart1, Product1 where Cart1.ProductId=Product1.Id and ClientID=@id and IsInCart=@cart", cn);
           // SqlCommand cmd = new SqlCommand("Select * from Cart1", cn);
            cmd.Parameters.AddWithValue("@id", clientId);
            cmd.Parameters.AddWithValue("@cart", true);
             da = new SqlDataAdapter();
            da.SelectCommand = cmd;
            SqlCommandBuilder cb = new SqlCommandBuilder(da);
            table = new DataTable();
            table.Locale = System.Globalization.CultureInfo.InvariantCulture;
            da.Fill(table);
            if (table.Rows.Count > 0)
            {
                // Automatically generate the DataGridView columns.
                GridView2.AutoGenerateColumns = true;

                // Set up the data source.
                GridView2.DataSource = table;



                // Set the DataGridView control's border.
                GridView2.BorderStyle = BorderStyle.Dotted;

                // Put the cells in edit mode when user enters them.
                GridView2.AutoGenerateEditButton = true;
                GridView2.AutoGenerateDeleteButton = true;
                GridView2.AllowPaging = true;
                GridView2.Visible = true;
                GridView2.DataBind();
                fillTotal();
            }
            else
            {
                litTotal.Text = "$ 0.00 ";
                litVat.Text = "$ 0.00";
                
                LitTotAmount.Text = "$ 0.00";
            }
        
        }
        protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
        {
            GridViewRow row1 = GridView2.Rows[e.NewEditIndex];

            int rowId = Convert.ToInt32(row1.Cells[1].Text);
            
            Response.Redirect("~/Pages/FloraEdit.aspx?id=" + rowId);

        }

        protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            GridViewRow row1 = GridView2.Rows[e.RowIndex];
            int rowId = Convert.ToInt32(row1.Cells[1].Text);
            cn.Open();
            string del = "delete from Cart1 where Id=@id";
            SqlCommand cmd = new SqlCommand(del, cn);
            cmd.Parameters.AddWithValue("@id", rowId);
            cmd.ExecuteNonQuery();
            cn.Close();


            table = new DataTable();
            table.Locale = System.Globalization.CultureInfo.InvariantCulture;
            da.Fill(table);

            if (table.Rows.Count > 0)
            {
                GridView2.AutoGenerateColumns = true;
                GridView2.DataSource = table;
                GridView2.BorderStyle = BorderStyle.Dotted;
                GridView2.AutoGenerateEditButton = true;
                GridView2.AutoGenerateDeleteButton = true;
                GridView2.DataBind();
                fillTotal();
            }
            else
            {
                litTotal.Text = "0.00kyats";
                litVat.Text = "0.00kyats";
                litTotal.Text = "0.00kyats";


            }


        }

        private void fillTotal()
        {
            cn = new SqlConnection(source);
            cn.Open();
            int tot = 0;

            SqlCommand cmd = new SqlCommand("Select Sum(Amount) from Cart1 where ClientID=@id and IsInCart=@cart", cn);

            cmd.Parameters.AddWithValue("@id", clientId);
            cmd.Parameters.AddWithValue("@cart", true);
            tot = Convert.ToInt32(cmd.ExecuteScalar());
            cn.Close();
            double vat = tot * 0.01;
            double totAmt = tot + 15 + vat;
            litTotal.Text = tot.ToString() + " kyats";
            litVat.Text = vat.ToString() + " kyats";
            LitTotAmount.Text = totAmt.ToString() + " kyats";
        }

        protected void Button1_ClickButton1_Click(object sender, EventArgs e)
        {
            GridView2.AutoGenerateDeleteButton = false;
            GridView2.AutoGenerateEditButton = false;

            string filename = Server.MapPath("Report.xls");
            Response.AppendHeader("content-disposition", "attachment; filename=" + filename);
            Response.ContentType = "application/vnd.ms-excel";


            StringWriter sw = new StringWriter();
            HtmlTextWriter ht = new HtmlTextWriter(sw);
            HtmlForm frm = new HtmlForm();
            p1.Parent.Controls.Add(frm);

            frm.Attributes["runat"] = "server";
            frm.Controls.Add(p1);
            frm.RenderControl(ht);
            Response.Write(sw.ToString());

            Response.End();
        }
    }
}